#!/bin/sh
export scripts="/storage/.kodi/addons/script.mecooltoolbox/resources/scripts/bash"

autor="fcoaaron"
export eval scripts_$autor=$scripts
#export eval scripts_$autor=$scripts\/$autor

function kodimsg {
	# Simple function to show a notification message to Kodi through kodi-send utility.
	# Usage: kodimsg "title" "message" [milliseconds]
	[ -n "$3" ] && local cmd="Notification(\"$1\",\"$2\",\"$3\")" || local cmd="Notification(\"$1\",\"$2\")"
	kodi-send -a "$cmd" &> /dev/null
}
function error {
	echo "ERROR: "$1
	kodimsg ERROR "$1"
}

function find_mostrecentfile {
	# Usage: result=$(find_mostrecentfile "<path>" "<filename>" <max_depth>)
	local res=$(find $1 -iname $2 -type f -size +1c -maxdepth $3 -print0 | xargs -0 ls -1 -t | head -1) &> /dev/null
	echo "$res"
}

function getmacaddr {
	# Usage: result=$(getmacaddr [device] <remove_colons>[true,false])
	# Example: result=$(getmacaddr eth0 true)
	local res=$(ifconfig $1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
	[ "$2" = "true" ] && echo $res | sed s/://g || echo $res
}
function sumonly {
	# Usage: result=$(sumonly <file>)
	echo $(md5sum $1 | cut -d" " -f1)
}

# Usage: result=$(readparam <file> <param>)
function readparam { echo $(cat $1 | tr -d ' ' | grep -w "$2" | cut -d"=" -f2); }

function reiniciar {
	case $1 in
		"oscam") systemctl restart service.softcam.oscam &> /dev/null ;;
		"kodi") systemctl restart kodi &> /dev/null ;;
		"skin") kodi-send -a "ReloadSkin()" &> /dev/null ;;
	esac
}
